[blue_loadout]
# Primary Color selection
team_color_id = 19
# Secondary Color selection
custom_color_id = 0
# Car type (Octane, Merc, etc)
car_id = 1295
# Type of decal
decal_id = 0
# Wheel selection
wheels_id = 4646
# Boost selection
boost_id = 3263
# Antenna Selection
antenna_id = 143
# Hat Selection
hat_id = 0
# Paint Type (for first color)
paint_finish_id = 279
# Paint Type (for secondary color)
custom_finish_id = 279
# Engine Audio Selection
engine_audio_id = 0
# Car trail Selection
trails_id = 1898
# Goal Explosion Selection
goal_explosion_id = 1908

[blue_loadout.paint]
# car_paint_id
car_paint_id = 12
# decal_paint_id
decal_paint_id = 0
# wheels_paint_id
wheels_paint_id = 12
# boost_paint_id
boost_paint_id = 12
# antenna_paint_id
antenna_paint_id = 0
# hat_paint_id
hat_paint_id = 0
# trails_paint_id
trails_paint_id = 8
# goal_explosion_paint_id
goal_explosion_paint_id = 12


[orange_loadout]
# Primary Color selection
team_color_id = 35
# Secondary Color selection
custom_color_id = 0
# Car type (Octane, Merc, etc)
car_id = 1295
# Type of decal
decal_id = 0
# Wheel selection
wheels_id = 4646
# Boost selection
boost_id = 3263
# Antenna Selection
antenna_id = 143
# Hat Selection
hat_id = 0
# Paint Type (for first color)
paint_finish_id = 279
# Paint Type (for secondary color)
custom_finish_id = 279
# Engine Audio Selection
engine_audio_id = 0
# Car trail Selection
trails_id = 1898
# Goal Explosion Selection
goal_explosion_id = 1908

[orange_loadout.paint]
# car_paint_id
car_paint_id = 12
# decal_paint_id
decal_paint_id = 0
# wheels_paint_id
wheels_paint_id = 12
# boost_paint_id
boost_paint_id = 12
# antenna_paint_id
antenna_paint_id = 0
# hat_paint_id
hat_paint_id = 0
# trails_paint_id
trails_paint_id = 10
# goal_explosion_paint_id
goal_explosion_paint_id = 12
